### PR TITLE
Modified 01 links to point landing pages

### PR DESCRIPTION
**Pull request by ystk**
This PR replace all 01 links to landing page for each segment. (Discussions were made in #419).
This PR also includes changes to point translated articles for Chinese and Japanese articles.
These changes were made by using sed command. I have tested the changes for one article in each segment only. But it should be okay because the other changes use exactly the same rule.

I hope these changes will pass the test in #428 .

### CODE REVIEW

**Comment by ystk** [comment]
I also have another changes for filename fixes. 
If you are okay, I would like to include the filename changes in this PR. 
You can see the changes at the following URL.
https://github.com/ystk/InnerSourceLearningPath/compare/landing-page-link...ystk:rename-filenames-for-translations

**Comment by rrrutledge** [comment]
Thank you, @ystk!  Will take a look at it probably in the next few days.  Have been on vacation.

**Review by tsadler1988 — APPROVED** [review]
Looks good to me, thanks @ystk! Manually checked a selection of the links and all were correct. #428 hasn't been picked up yet, so just manually reviewing and checking for now 😄 

I see the file name changes haven't been included, assume you'll make a separate PR for that?

**Comment by ystk** [comment]
> I see the file name changes haven't been included, assume you'll make a separate PR for that?

Yes, I will. Before making the changes, I try to resolve merge conflicts on #427 .

**Pull request merged**
