### PR TITLE
#382 creation of german index.md files

### PR DESCRIPTION
**Pull request by RJPlog**
Hi Tom, I created german translations of the md files as you suggested for each section. I put it into the ../de folder. 

In the introduction file you have a variable featured: true, I just kept that, even if not knowing what it means and why it is not in the other sections.

Please let me know if I have some misunderstanding.

@lenucksi maybe you would like to review the translation.

### CODE REVIEW

**Comment by lenucksi** [comment]
Excellent @RJPlog, thanks a lot. I'll happily review them and get them merged. Might even happen today evening.

**Review by lenucksi — APPROVED** [review]
These changes look are crisp and easy to understand. Also, I could not find any mistakes with regard to spelling or grammar. 
This looks good to merge to me.

@tsadler1988 Do you want to give the mentioned front matter variable a look and maybe add needed changes as commit suggestions?

**Comment by tsadler1988** [comment]
Thanks for jumping on this so quickly @RJPlog!

Do we want to translate the titles, or all these all terms that we don't translate?

**Comment by tsadler1988** [comment]
> In the introduction file you have a variable featured: true, I just kept that, even if not knowing what it means and why it is not in the other sections.

Yes this is correct, it means the Introduction section will appear larger on this page:

image

**Comment by RJPlog** [comment]
Thanks for explaining the matter with the 'featured', understood. Concerning the translation of the headings, we once said we will not translate keywords link learning path/trusted committer..... So in oder to follow the translations in the sections I also left it as it is, only with introduction I felt it would look better if this one will be translated into german. Means, this was done on purpose, but I  am happy to change if you suggest to do so

**Comment by tsadler1988** [comment]
I thought that might be the case, thanks for clarifying @RJPlog. Approved 😄 .

**Review by tsadler1988 — APPROVED** [review]

**Comment by rrrutledge** [comment]
Great work everyone!

**Pull request merged**
