### PR TITLE
#382 added italian index.md for contributor and introduction

### PR DESCRIPTION
**Pull request by OpenPj**
I have just added the new index.md files for the current sections translated in italian. Hope during the next few days to  work on more chapters

### CODE REVIEW

**Review by lenucksi — COMMENTED** [review]
This looks great to me - thanks for creating it! :tada: 
Do you possibly know another native Italian speaker who could provide a review as I don't speak Italian to any degree unfortunately?

**Comment by rrrutledge** [comment]
> This looks great to me - thanks for creating it! 🎉
> Do you possibly know another native Italian speaker who could provide a review as I don't speak Italian to any degree unfortunately?

@dottorblaster has reviewed in the past.

**Comment by dottorblaster** [comment]
And here I am, happy to serve :smile: 

I'm reviewing this in a while, thanks for asking!

**Review by dottorblaster — APPROVED** [review]
LGTM

**Comment by lenucksi** [comment]
> LGTM

Thanks for the review @dottorblaster! Merging it then!

**Pull request merged**
