### PR TITLE
Update pair programming language

### PR DESCRIPTION
**Pull request by nktrk**

### CODE REVIEW

**Comment by nktrk** [comment]
From the [discussion in Slack here](https://innersourcecommons.slack.com/archives/CARTU4XV2/p1662135964011079)

**Review by rrrutledge — APPROVED** [review]
This looks great, @nktrk ❗️

**Review by lenucksi — APPROVED** [review]
Thanks for adding this @nktrk! I think it's a good clarification.

**Comment by rrrutledge** [comment]
It's [live](https://innersourcecommons.org/learn/learning-path/introduction/workbook/).  Well done ❗

**Pull request merged**
