### PR TITLE
Italian translation of the Contributor section

### PR DESCRIPTION
**Pull request by OpenPj**
This is the italian translation of the Contributor section.
Hope this helps
^__^

### CODE REVIEW

**Comment by rrrutledge** [comment]
Wow!  So great!  Maybe @dottorblaster could have a look again?

**Comment by dottorblaster** [comment]
Oh wow, sure!

**Comment by rrrutledge** [comment]
Hey @dottorblaster, thanks so much for being willing to have a look!  Just wanted to remind if it works out for you to have time on this?  If not that's OK, too, just let us know.  Thanks!

**Comment by dottorblaster** [comment]
@rrrutledge thanks for the reminder, I actually have some comments pending and I have to finish up the review, I was slower than I thought, sorry!

**Review by dottorblaster — CHANGES_REQUESTED** [review]
@OpenPj astonishing work! Some comments and I think it'll be fine :smile:

**Comment by rrrutledge** [comment]
Thank you so much for reviewing, @dottorblaster ❗

**Comment by dottorblaster** [comment]
@rrrutledge no problem! Can I ask you to appear in some proofreading credits maybe? I consider this a valuable contribution :heart:

**Comment by rrrutledge** [comment]
@dottorblaster can you make one of your PR comments as a commit suggestion instead of text comment?  I believe that will cause your name to show up in the contributors list automatically, based on _GitHub_ commit history.

**Comment by dottorblaster** [comment]
@rrrutledge I'll try, thanks for the suggestion!

**Comment by dottorblaster** [comment]
@rrrutledge I turned every comment to a suggestion, this way you or @OpenPj can directly commit the changes and the review should be very smooth.

**Comment by rrrutledge** [comment]
That is so awesome, @dottorblaster!  Easier to review and you get the credit that you surely deserve!

**Comment by dottorblaster** [comment]
It sure isn't a matter of deserving, it's much more a thing like "I wanna proudly show I was part of this", I'm learning a lot about team collaboration through this and in fact I wanted to thank you and @OpenPj :-)

**Comment by OpenPj** [comment]
Sorry for this delay, I finally reviewed all the improvements suggested by @dottorblaster 😅 
Thank you so much for your review!

**Review by dottorblaster — APPROVED** [review]
Amazing!

**Review by rrrutledge — APPROVED** [review]
Great work all!

**Comment by rrrutledge** [comment]
Will work over the upcoming week to get this on the website.

**Pull request merged**
