### PR TITLE
Create 01-introduction-pt-br.asciidoc

### PR DESCRIPTION
**Pull request by nysenthil**
Machine translated content of LP1 article in pt-br ready for manual verification by @fer-correa 

Hi @fer-correa Do you have the instructions to properly verify the machine translated content by comparing it with the original English content? If needed, please tell me so that I can email you the detailed instructions.

### CODE REVIEW

**Comment by fer-correa** [comment]
Hi @nysenthil.
Could you share the instructions with me?

**Comment by fer-correa** [comment]
✅ 

Thanks guys, for the opportunity to participate 👍

**Review by nysenthil — COMMENTED** [review]
Hi Fernando,
First of all, thanks very much for agreeing to do the manual verification of the machine translated Learning Path articles. It is amazing work by you with a quick turnaround. We are going to rely on you to do the manual verification of six more LP articles as we do machine translation of them to pt-br. I'm approving your changes and then I will merge it to the main branch.

**Comment by fer-correa** [comment]
Great @nysenthil ,
It will be a pleasure to continue working on it.

**Review by rrrutledge — APPROVED** [review]

**Pull request merged**
