### PR TITLE
Polished the Chinese translation of introduction

### PR DESCRIPTION
**Pull request by WillemJiang**

### CODE REVIEW

**Comment by rrrutledge** [comment]
Great, @WillemJiang!  Let's see if there can be some native speaker reviews of https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/314 and then direct them here afterward.

**Review by tanzhongyi003 — APPROVED** [review]
Looks good. thanks, willem

**Review by lenucksi — COMMENTED** [review]
Excellent, thank your for the updates and polishing @WillemJiang and thanks for the LGTM @tanzhongyi003 :tada: 

However, we now have a merge conflict in one of the introduction files that I can't resolve myself due to not speaking Chinese. Could you please take a look at that @WillemJiang?
Happy to merge afterwards.

**Comment by WillemJiang** [comment]
@lenucksi  I just resolved the conflicts.  Please feel free to merge it.

**Review by tanzhongyi003 — APPROVED** [review]
LGTM

**Review by rrrutledge — APPROVED** [review]
If it's good for you, then it's good for me.

**Pull request merged**
