### PR TITLE
Post Production - Issue 16

### PR DESCRIPTION
**Pull request by stuartpurgavie**
https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/16
Update to use "program" instead of "project" to align with voice track
On slide titled "Top 5 Common Complaints"
Update in master presentation document and exported screen captures

### CODE REVIEW

**Comment by lenucksi** [comment]
> #16
> Update to use "program" instead of "project" to align with voice track

I see it updated as ```product``` instead of ```project``` - it sounds plausible and I haven't heard the audio for a while, but is that desired?

**Comment by stuartpurgavie** [comment]
@lenucksi the purpose of this PR was to bring the audio and visual tracks in line. I'm not able to modify the voice track using a PR, so this was all I could do to promote consistency.

If word choice is a concern of yours, then we could define the words and then get specific? From my understanding of IT PMO, "program" is an overarching term to describe a collection of "projects" that implement or modify an application stack for a given purpose, so the use of "program" here may be appropriate. However, it could also be a jargon use that is more confusing for technical audience members, as for many "program" and "application" are analogous terms.

**Comment by lenucksi** [comment]
> @lenucksi the purpose of this PR was to bring the audio and visual tracks in line. I'm not able to modify the voice track using a PR, so this was all I could do to promote consistency.

I'm fully onboard with this and think it's good. 

My comment should've read
> I see it updated as ```product``` instead of ```program``` - it sounds plausible and I haven't heard the audio for a while, but is that desired?

As in, your original PR description said "update to program" but the new slide says "product" which is incosistent and the reason for me to ask I something at either location was a typo. Maybe I also just didn't find the place where it was changed as described in the PR. 

> If word choice is a concern of yours, then we could define the words and then get specific? From my understanding of IT PMO, "program" is an overarching term to describe a collection of "projects" that implement or modify an application stack for a given purpose, so the use of "program" here may be appropriate. However, it could also be a jargon use that is more confusing for technical audience members, as for many "program" and "application" are analogous terms.

I agree with you that this is a potentially confusing overlap of words but not something I would change in the slides or address here. Maybe in a sentence in the article that goes with the video.

**Comment by lenucksi** [comment]
#96 is relevant for the assignments.md file here.

**Comment by rrrutledge** [comment]
Sorry folks, I've been on vacation, but I just double-checked and the slides in this pull request now match the current audio.

**Comment by rrrutledge** [comment]
Great work, @stuartpurgavie !

**Pull request merged**
