### PR TITLE
Update 01-introduction.asciidoc

### PR DESCRIPTION
**Pull request by SJVle**
Punctuation,  do we let the "Traduit avec www.DeepL.com/Translator (version gratuite)" ?

### CODE REVIEW

**Comment by lenucksi** [comment]
> Punctuation, do we let the "Traduit avec [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (version gratuite)" ?

Thanks for creating this. I'd like to remove the DeepL line, but I'm not 100% if we need to state any attribution to using their service. Do we have people with opinions on that? I couldn't find anything indicating need to attribution myself.

**Review by lenucksi — APPROVED** [review]
Language-Change wise this looks good to me. So approval from me.

**Comment by rrrutledge** [comment]
> I'd like to remove the DeepL line, but I'm not 100% if we need to state any attribution to using their service. Do we have people with opinions on that? I couldn't find anything indicating need to attribution myself.

Discussed some reasons on the call to leave it in.

**Comment by lenucksi** [comment]
Thanks again for creating this @SJVle :tada: :smile: 
Merging this in!

**Pull request merged**
