### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by rrrutledge**
Ported from https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/523/files.

### CODE REVIEW

**Comment by spier** [comment]
Dang, I am just realizing that with the changes pulled into this separate PR I might have missed my only chance to become a LearningPath contributor :) Just kidding.

**Comment by rrrutledge** [comment]
Haha I thought about trying to be fancy and pull in your commits somehow but just copy/pasted instead.  You could have had your name on some articles, yes.

**Comment by spier** [comment]
No worries. I will get another chance.

And yeah, either cherry-picking the commits or using GitHub's [Co-authored-by](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) syntax would have been a way to solve this.

**Comment by rrrutledge** [comment]
Good idea!

**Pull request merged**
