### PR TITLE
add zh translation for product owner

### PR DESCRIPTION
**Pull request by tanzhongyi003**

### CODE REVIEW

**Comment by rrrutledge** [comment]
Awesome, @tanzhongyi003!  Have you been able to try out generating the pages and running the website?

**Comment by tanzhongyi003** [comment]
yes，I followed your suggested steps, generate the files, and run jekyll to check the contents.
when check is done, I submit the PR.

**Comment by rrrutledge** [comment]
Tagging a few people that have had work reviewed by @tanzhongyi003.  @WillemJiang / @niminghong / @adadai88 / @yvonneT1 would you have time to review?

**Review by WillemJiang — APPROVED** [review]
LGTM.

**Review by rrrutledge — APPROVED** [review]

**Pull request merged**
