### PR TITLE
Fix user tile bug

### PR DESCRIPTION
**Pull request by rrrutledge**
* For some reason, some author objects in the graph API are missing a user object (and subsequently a user URL).
* Users without a URL don't get a link to their GitHub profile.
* Fix is to explicitly ensure that we don't overwrite a good user URL with an empty one.
* See https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/536

### CODE REVIEW

**Comment by rrrutledge** [comment]
A better fix would be to figure out why some author objects in the API are getting returned without a user, but I couldn't see how to make much headway, there.

**Review by nysenthil — APPROVED** [review]
This morning, I discussed this PR with Russ and he explained his code changes. His tests ran fine as well. I'm approving this change.

**Comment by nysenthil** [comment]
This morning, I discussed this PR with Russ to go over his code changes. All looks good. I'm approving and merging this PR now.

**Comment by rrrutledge** [comment]
Looks good!

**Pull request merged**
