### PR TITLE
Initial move of TC workbook from GoogleDoc to GitHub

### PR DESCRIPTION
**Pull request by lenucksi**
This pull request contains the Trusted Committer section of the Learning Path Google Doc moved. 
- Currently in blank form, will be transformed to ASCIIdoc later. 
- However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

### CODE REVIEW

**Comment by rrrutledge** [comment]
> * However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

Can you give me permission to create a branch in your project fork? I think that making a branch with all of the suggestions would be easier than a bunch of separate commit suggestions.

**Comment by lenucksi** [comment]
> > * However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.
> 
> Can you give me permission to create a branch in your project fork? I think that making a branch with all of the suggestions would be easier than a bunch of separate commit suggestions.

I can but it should work equally well if you pull my branch to your fork and then make a pull request against mine. Alternatively I could also just place this in a branch in the main repo.

**Comment by rrrutledge** [comment]
Branch in the main repo is easiest of all, assuming that works for you.

**Comment by lenucksi** [comment]
Just decided to let `sed` run wild on the document, markup should be good to go now.

**Pull request merged**
