### PR TITLE
Translation-ja: Add product-owner/ja/03-major-benefits

### PR DESCRIPTION
**Pull request by ystk**
This PR relate to #407 to add a Japanese translation for the third section of Product Owner chapter.

### CODE REVIEW

**Review by rrrutledge — APPROVED** [review]
Good catch.

**Comment by ystk** [comment]
Hi @rrrutledge 
The first commit in this PR still needs to be reviewed by others.
I think there are several possible approaches. One is create a new pull request by reviewer. And the other one is revert this changes.
Apologies for this confusion.

**Comment by rrrutledge** [comment]
Revert is fine.  Sorry I didn’t notice the translation - just the broken link fix.

**Comment by johtani** [comment]
I'll check soon :)

**Comment by ystk** [comment]
I opened a new PR to revert this PR and add the same document (03-major-benefits) for review.

**Comment by rrrutledge** [comment]
Thanks for helping to fix this.  I merged the other PR.

**Pull request merged**
