### PR TITLE
Reduce manual steps for adding new translations

### PR DESCRIPTION
**Pull request by tsadler1988**

### CODE REVIEW

**Comment by lenucksi** [comment]
This looks good to me so far. Could you link how the language detection is now done?
Also, @rrrutledge might want to take a look on the JS parts.

**Comment by tsadler1988** [comment]
> Could you link how the language detection is now done?

It's inferred from the directory structure:
```
    const translations = fs.readdirSync(baseReadPath, { withFileTypes: true })
      .filter(dirent => dirent.isDirectory())
      .map(dirent => dirent.name)
```

And the now deleted language map has been replaced by more generic language for placeholder index pages e.g. `This text will be translated soon.` rather than `This text will be translated soon to French.`.

**Review by rrrutledge — APPROVED** [review]

**Comment by tsadler1988** [comment]
Thanks for the 👍  @rrrutledge, I'll merge it in now.

**Comment by rrrutledge** [comment]
Great!  Thanks for this work, Tom.

**Pull request merged**
