### PR TITLE
WIP: Addition of initial Slide state, more to be added.

### PR DESCRIPTION
**Pull request by lenucksi**
This pull request adds the current state of the Google slides in the following forms
 - exported PDF 
 - PDF converted to PNGs

See `convert.sh` for the using conversion mechanism and settings.

Expect slide update to this pull request or the slides in further pull requests.

This is likely of interest to @clobner.

### CODE REVIEW

**Comment by lenucksi** [comment]
Added updates slides incorporating all present changes. Added the raw slide sets too. 
The used font according to Google Slides is "Helvetica neue".

**Comment by rrrutledge** [comment]
Could be good to put these into folders grouped by video segment name.

**Comment by rrrutledge** [comment]
Are these the final "stickman" images?

**Comment by lenucksi** [comment]
> Could be good to put these into folders grouped by video segment name.

I agree. This PR is across two branches of this repo to enable exactly such things, hence be welcome to add the required commits to do exactly that! :)

**Pull request merged**
