### PR TITLE
Create 01-introduction-it.asciidoc

### PR DESCRIPTION
**Pull request by nysenthil**

### CODE REVIEW

**Comment by lenucksi** [comment]
Probably @fioddor is one of the best reviewers here.

**Comment by rrrutledge** [comment]
@OpenPj has done Italian work here in the last as well.

**Comment by nysenthil** [comment]
A long time colleague in my IBM building @pdettori is a native speaker of the Italian language. He allocated his time to do the required verification of the machine translation done by the IBM Watson Language Translator tool.

**Comment by OpenPj** [comment]
> @OpenPj has done Italian work here in the last as well.

Hi folks,
I'm sorry I saw this too late :-P

**Comment by rrrutledge** [comment]
Thanks for checking in, @OpenPj ❗️  It’s nice to hear from you 🙂.

**Pull request merged**
