### PR TITLE
Sloppy translation as baseline for issue 460

### PR DESCRIPTION
**Pull request by fioddor**
Just a sloppy translation as baseline for teasing true french speakers into applying serious corrections. See #460.

### CODE REVIEW

**Comment by fioddor** [comment]
Please, @SJVle, review.

**Comment by rrrutledge** [comment]
> why github doesn't allow me

Need to invite the person as a collaborator to the project first.

**Comment by SJVle** [comment]
Hello,
In hollidays, I shall see that next week.
Tchuss
----- Mail d'origine -----
De: rrrutledge ***@***.***>
À: InnerSourceCommons/InnerSourceLearningPath ***@***.***>
Cc: Vincent Legault ***@***.***>, Mention ***@***.***>
Envoyé: Sat, 23 Apr 2022 13:21:34 +0200 (CEST)
Objet: Re: [InnerSourceCommons/InnerSourceLearningPath] Sloppy translation as baseline for issue 460 (PR #470)

> why github doesn't allow me

Need to invite the person as a collaborator to the project first.

**Comment by SJVle** [comment]
Hi I can't find the file to review... i'm not so used ti git :(

**Comment by tsadler1988** [comment]
@nysenthil links to English and French as requested:
[English](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/692fd812da302e52b240aab50bb569ccd269828e/trusted-committer/01-introduction.asciidoc)
[French](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/692fd812da302e52b240aab50bb569ccd269828e/trusted-committer/01-introduction-fr.asciidoc)

**Comment by nysenthil** [comment]
Today, I got help from my IBM colleague (Lionel Villard) here in Yorktown Heights, NY to verify the Engligh to French machine translated text. I'm attaching the output of our verification work here. In the next few days, Travis and I will work to get it in proper form in the pull request so that it can be committed.

[01-Introducing-The-Trusted-Committer-Role-English-To-French-Verification.txt](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/9004755/01-Introducing-The-Trusted-Committer-Role-English-To-French-Verification.txt)

[02-Introducing-The-Trusted-Committer-Role-French-Verification.txt](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/9004757/02-Introducing-The-Trusted-Committer-Role-French-Verification.txt)

**Comment by rrrutledge** [comment]
Thank you @ladji103 ❗

**Comment by rrrutledge** [comment]
And thank you, @lionelvillard ❗

**Review by rrrutledge — APPROVED** [review]
Go team 🎉 ❗

**Pull request merged**
