### PR TITLE
#321 Added the Chinese translation of product owner

### PR DESCRIPTION
**Pull request by WillemJiang**

### CODE REVIEW

**Comment by lenucksi** [comment]
Excellent, thank you for translating these articles @WillemJiang! :tada: 

You might have noticed that their writing style differs a bit from the other articles which is caused by their history. Hence, larger changes to phrasing, formating, etc that make it easier to read are also welcome.

I'm happy to merge this once it is reviewed by another native speaker.

**Review by tanzhongyi003 — APPROVED** [review]
LGTM

**Review by rrrutledge — APPROVED** [review]

**Comment by rrrutledge** [comment]
@WillemJiang this work is fantastic!  Now that the content is "in" we want to get it on the innersourcecommons.org website.  Would you like to learn how to do so?  Check out these instructions: [How to update innersourcecommons.org with new articles
](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/scripts#how-to-update-innersourcecommonsorg-with-new-articles).

Let me know if it's something you want to try to take a crack at doing.

**Comment by tanzhongyi003** [comment]
I will submit a merge request next week to update it.

**Comment by rrrutledge** [comment]
Awesome, @tanzhongyi003.  It will be great to see this work on innersourcecommons.org

**Pull request merged**
