### PR TITLE
Raw, edited content from the Atlas TC repo.

### PR DESCRIPTION
**Pull request by lenucksi**
## Content
This pull request represents the editorial content in the Trusted Committer repository in Atlas. 
It leaves out the material such as the TOC, the front matter and build configuration.

There are no content edits made to it by me. 
There are many great edits by the O'Reilly editors, however also some parts where our codebase possibly has things that might be worth to incorporate or others that we might want to change.

This handles #157.
Added @gruetter for review since the text has been written by him to a relevant degree. 

## Todo 
If we want to use this to enable automatic sync of Upstream to Atlas and final review on GitHub we'll need to incorporate / merge these changes with our repo dealing with above differences.

- Add decent sync points to enable decent web diffing. 
  - See [here](https://github.com/InnerSourceCommons/InnerSourceLearningPath/compare/atlas/tc-edited-sources?expand=1#diff-1ff22a5a496ebe237f53da680d9c616bL45) and [here](https://github.com/InnerSourceCommons/InnerSourceLearningPath/compare/atlas/tc-edited-sources?expand=1#diff-1ff22a5a496ebe237f53da680d9c616bR50) for an example. Dealt with by adding matching commits with the proper line breaks etc..
- Review the cross chapter linking and figure out the correct way to do this for O'Reilly.
 - If we link external content, such as the patterns, figure out a way to link them properly 
- Review the actual content
- Check out the build results (PDF/Epub) to enable the final sign-off for O'Reilly to put them on the platform. See #58 for this.

### CODE REVIEW

**Comment by rrrutledge** [comment]
Thanks, Johannes!  Will look at this next week.

**Comment by rrrutledge** [comment]
It's too bad there isn't a cleaner diff so that we can see exactly what were the changes from O'Reilly.  It's nice to have this content, though.

**Comment by lenucksi** [comment]
> It's too bad there isn't a cleaner diff so that we can see exactly what were the changes from O'Reilly. It's nice to have this content, though.

That's exactly what adding a few changes to create better sync points for the GitHub diff algorithm is supposed to help us with.

**Comment by lenucksi** [comment]
Closing this for now in favor of #205.

**Pull request closed without merging**
