### PR TITLE
Update 01-introduction-zh.asciidoc

### PR DESCRIPTION
**Pull request by jupeng1982629**
translate innersource to “内源”，because more chinese know this chinese word a little, additionally, we could let more people accept this "内源".

### CODE REVIEW

**Comment by WillemJiang** [comment]
I agree with @jupeng1982629 to use "内源" for the InnerSource in  Chinese.
@tanzhongyi003  what do you think about it?

@jupeng1982629  we may need to do the find and replace in the whole directory once we agree to use "内源" directly.

**Comment by jupeng1982629** [comment]
> I agree with @jupeng1982629 to use "内源" for the InnerSource in Chinese.
> @tanzhongyi003 what do you think about it?
> 
> @jupeng1982629 we may need to do the find and replace in the whole directory once we agree to use "内源" directly.

@WillemJiang ok, I will do so, after we all accept this. @tanzhongyi003

**Comment by rrrutledge** [comment]
Great conversation, sounds like.  Glad this all is getting figured out.

**Comment by rrrutledge** [comment]
Should `InnerSource` be translated?  Other languages have opted purposefully not to translate it.

**Comment by jupeng1982629** [comment]
> Should `InnerSource` be translated? Other languages have opted purposefully not to translate it.

@rrrutledge Hi, Rutledge, very glad to recieve your reply. In China, more and more young engineer know OpenSource as chinese word "开源"，of cource, they all know this is from English OpenSource. And more good developer in them will join in OpenSource to contribute their achievement to the world. this is a procedure, we call it "融入"，we all want to join in the world. Select a good chinese word to let more chinese accept it, is important for this procedure. When more people talk this chinese word according to the english word which it come from, this will let they be more  confident to let others know they are internationalized. Connection to Others is welcome in chinese. So, This happened so many times during the long china history, One is the OpenSource to "开源"， so as to Basing on my understanding "开源"，I can understand "内源" immidiately when Willem talk it to me. This is why I translate it to "内源". Maybe this is not conform to our group routine, sorry, I just take it on my chinese custom.

**Comment by tanzhongyi003** [comment]
Hi, Jupeng,   when we begin to translate these documents into Chinese, 
we discussed that we follow the same rule in translation, including not translate some words, including "InnerSource", "Trusted Committer", because translate these words may cause confusion.
so we modified our original patches, and keep "InnerSource" there.

hope you can understand.
thanks

**Comment by WillemJiang** [comment]
Thanks for the comment from @tanzhongyi003 . 
I just found the [contribution document ](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/CONTRIBUTING.md#translations) mentioned about it.

**Comment by jupeng1982629** [comment]
@tanzhongyi003 ok, understand, so I close this.

**Comment by rrrutledge** [comment]
Hey all, thanks for these comments.  I want to call out that the contribution document was based off of European language and culture.  I am open to the idea that for the Chinese language and culture it may be more appropriate to translate the word.  I don't know and want you all to chime in with your thoughts.

Does `内源` make more sense in the Chinese language and culture than `InnerSource`?  I don't want to prematurely cut off conversation on this question just because the contribution document already got some guidance on it from our European contributors.

**Comment by tanzhongyi003** [comment]
let us keep using "InnerSource" for now,  then see if we need to change it in the near future.

**Comment by jupeng1982629** [comment]
> from our Europea

Hi, Rutledge, I don't wanna say "内源" make more sense than InnerSource. They are at the same level when people accept a new concept, at different system of language. this is a usual phenomenon that is not distinct when European learn from English. Because they all in the same system of language. if there is a new english word with a new things which is knowing to German, they can use this english word directly. In other place, such as in Japan, lots of English word, is spoken by Japanese at their Japanese pronunciation, which also happened in India and some other Asia area. For Example, there is a word "con' to' lo' lu'", I type in pronunciation, cause I havn't install Japanese language in my computer, this word is from English "Con't'ro'l". This should be called mixed up. When we learn english, we will have some connections between English word, Chinese word and some pronunciation, even some story in our mind to remember this English word. After that we say we accept it totally. It's not easy to let all the chinese to speak a English word to instead of a concept, but it's easy to use a chinese word to let them associate this English word and concept. For Example. "麦当劳" to "Mcdonald's", "肯德基" to “KFC”, "奔驰" to “Benz”，“开源” to “OpenSource”, So many as I can't count them all. 

Chinese are in a long time to learn to respect fusion and discipline. So we will follow the principles and rules of Organization.
So I will use "InnerSource" everywhere in Chinese translations, and without mention about "内源". untill Owners agree we put them together.

**Comment by jupeng1982629** [comment]
> Hey all, thanks for these comments. I want to call out that the contribution document was based off of European language and culture. I am open to the idea that for the Chinese language and culture it may be more appropriate to translate the word. I don't know and want you all to chime in with your thoughts.
> 
> Does `内源` make more sense in the Chinese language and culture than `InnerSource`? I don't want to prematurely cut off conversation on this question just because the contribution document already got some guidance on it from our European contributors.

Hi, Rutledge, I don't wanna say "内源" make more sense than InnerSource. They are at the same level when people accept a new concept, at different system of language. this is a usual phenomenon that is not distinct when European learn from English. Because they all in the same system of language. if there is a new english word with a new things which is knowing to German, they can use this english word directly. In other place, such as in Japan, lots of English word, is spoken by Japanese at their Japanese pronunciation, which also happened in India and some other Asia area. For Example, there is a word "con' to' lo' lu'", I type in pronunciation, cause I havn't install Japanese language in my computer, this word is from English "Con't'ro'l". This should be called mixed up. When we learn english, we will have some connections between English word, Chinese word and some pronunciation, even some story in our mind to remember this English word. After that we say we accept it totally. It's not easy to let all the chinese to speak a English word to instead of a concept, but it's easy to use a chinese word to let them associate this English word and concept. For Example. "麦当劳" to "Mcdonald's", "肯德基" to “KFC”, "奔驰" to “Benz”，“开源” to “OpenSource”, So many as I can't count them all.

Chinese are in a long time to learn to respect fusion and discipline. So we will follow the principles and rules of Organization.
So I will use "InnerSource" everywhere in Chinese translations, and without mention about "内源". untill Owners agree we put them together.

**Comment by WillemJiang** [comment]
I agree with @jupeng1982629  as we use "开源” for "OpenSource“ in Chinese.  It makes sence to use "内源“ for "InnerSource". For the "Trusted Committer", it's hard for me to find a right Chinese word to mention this role.

**Comment by jupeng1982629** [comment]
> I agree with @jupeng1982629 as we use "开源” for "OpenSource“ in Chinese. It makes sense to use "内源“ for "InnerSource". For the "Trusted Committer", it's hard for me to find a right Chinese word to mention this role.

@WillemJiang Hi，Willem，It's surely, really, totally hard to find a suitable chinese word to translate role name "Trasted Committer", especially After I read pages of it, https://innersourcecommons.org/resources/learningpath/trusted-committer/zh/04/

While I understand all these dutys of this role, I still can not tell a good visual figure of it.
To me, I am the Owner of BepCloud, to let others understand, it's internal plateform, if I find a trusted committer work for me, I will say this man is my "心腹"，to tell others he is trusted by me, and if you all trust me, he will work as me, please trust him. if we use a chinese style to name this role, I will say "授信提交代表"，that means "trusted committer representative", this "代表"（representative）in chinese has more meaning than it in English. this role usually present in some central committee summit meeting, they are responsible for lots of members which follows or has same job as them. all these representative must be  training and testing at many important aspects, so self-evidently they are trusted "授信的". So, “committer rep” is full-scale enough to figure out it.

**Comment by lenucksi** [comment]
Interesting insights made by @jupeng1982629 and @WillemJiang. Looking forward to hear the others opinion.

**Pull request closed without merging**
