### PR TITLE
Format and link

### PR DESCRIPTION
**Pull request by SJVle**
Last (?) corrections : format, links,and so on.

### CODE REVIEW

**Comment by SJVle** [comment]
@lenucksi fyi

**Review by lenucksi — APPROVED** [review]
Thanks @SJVle for these changes. :tada:  I'll prepare the next chapter for review soon!

**Comment by ystk** [comment]
This PR can be closed without merge. Because the #439 includes all changes in this PR.

**Comment by SJVle** [comment]
Is that Ok ? I did resolve 3 conflicts.

**Comment by lenucksi** [comment]
> Is that Ok ? I did resolve 3 conflicts.

That's indeed true. I just checked and there are three additional changes (newlines, one full stop) we can now merge since #439 resolved the merge conflict. So both PRs are good and can be merged. Thanks to both of you!

**Comment by rrrutledge** [comment]
Nice work!

**Pull request merged**
