### PR TITLE
Add revisioned slides for PO videos (Segment 4)

### PR DESCRIPTION
**Pull request by maxcapraro**
This MR revises the slides to the PO videos:
- Contents mainly by @Silona 
- Incorporated review feedback by @rrrutledge and @maxcapraro 
- Used styling/layout similar to the TC slides designed by @gruetter

### CODE REVIEW

**Comment by maxcapraro** [comment]
I'd love to get feedback and then consensus before sending the slides out to O'Reilly.

**Comment by maxcapraro** [comment]
Thank you @gruetter. You reviewed this _like a bosch_ :-)

I can't take credit for the contents of the slides because they were done by @Silona (minus some changes after a review by Russ and me).

I think all of your comments make a lot of sense. I'll incorporate them directly. Regarding the questions raised, it would be great if @Silona could tap into the discussion.

**Comment by rrrutledge** [comment]
Awesome, @maxcapraro.  I agree with everything from @gruetter.  Also these comments.

> 03_body_pt1-01_difficulties-02
* This slide will have to come in a bit later than its appearance in the current video because the text that is in the bullet is spoken a few seconds later by Silona.
> 04_body_pt2-01-benefits-01
* Recommend "You can get **other teams to help**" (no additional text).
> 04_body_pt2-01
* Is there another slide to create for this video segment (starting at `05:47`)?
> 06_recap_takeaways-02-wrapup-02
* Should the sub-bullets appear one-by-one?
* Need a sub-bullet for `Internal marketing`?

**Comment by maxcapraro** [comment]
I provided some updates. Because the diff view doesn't work well for PNG files, I summarized the changes below (using :heavy_check_mark: and :warning: as visual support). Thanks again to both of you for the excellent and detailed review! :)

- - - -
@gruetter's review:


> - 02_primer-01_requirements: 
>   - `s/process/processes`
>    - `s/Have basic/Have a basic`
>    - `s/committer'/committer` and `s/contributor's/contributor` (as per recommendation of my buddy from the UK)

✔️ Fixed
> - 03_body_pr1-02_complaints
>    - `s/in fighting/infighting`

✔️ Fixed
	
	
> - 04_body_pt2-01_benefits
>    - Proposal: `s/Open code/Code is accessible`
>    - Proposal: `s/Planning is transparent`
>    - Proposal: `s/Documentation is accessible`

✔️ Fixed

>    - What are you referring to with _negotiations_, @maxcapraro ? With agile and InnerSource, too (IMHO), the developers have more say than in other models.

:warning: I pinged @Silona. For now, I just dropped it.

> - 04_body_pt2-03-examples
>    - not sure what _Refactorization_ is ;). I'd say the modularisation is a result of the refactoring, if I understand this right. So maybe `s/and/and, as a result,` Also, _Payments_ is referring to PayPal, I guess. Do we need to write that here?

There are multiple important remarks in your comment:

- :heavy_check_mark: The term `refactorization` is much less common than `refactoring` --> Renamed it
- :warning: Relationship between modularization and refactoring: Many would probably agree with Georg's reading that modularization is a part of a refactoring effort. But if we stay with the (commonly used?) terminology by Martin Fowler, then I'd say refactoring (applying a series of small transformations) and modularization can very well be independent efforts --> I have a slight guts feeling to stay with "Refactoring and modularization"
- :warning: I watched that segment again, with that comment in mind. I think the audio/video is too light on establishing such context (Paypal context) for the viewer. I don't know how fixes could look like (other than rewriting + reshoting that).

>    - Is there a benefit for _ALM_ and _FDI_ as well, or are there related metrics which have improved? If so, I propose we spell that out here.

:warning: No metric catched my eye. It's more a qualitative than quantitative report.

	
> - 06_recap_takeaways-01-wrapup
>    - Proposal: `s/Middle management is tough/Being a middle manager can be tough`
>    - `s/planing/planning`

✔️ Fixed

	
> - 06_recap_takeaways-02-wrapup
>    - the abbreviation _TC_ has not been used or introduced on previous slides. Proposal: `s/TCs/Trusted committers`
	
✔️ Fixed

- - - - -
@rrrutledge's review:

>> 03_body_pt1-01_difficulties-02
>* This slide will have to come in a bit later than its appearance in the current video because the text that is in the bullet is spoken a few seconds later by Silona.

✔️ Fixed (added this to Screenlight)


>> 04_body_pt2-01-benefits-01
>* Recommend "You can get **other teams to help**" (no additional text).

✔️ Fixed. Good idea!

>> 04_body_pt2-01
>* Is there another slide to create for this video segment (starting at `05:47`)?

:warning: Yes, this is the one, where I had reached out to @Silona in Slack. With the current contents, I'd rather leave the slide out completely. I'll ask her again.


>> 06_recap_takeaways-02-wrapup-02
>* Should the sub-bullets appear one-by-one?
>* Need a sub-bullet for `Internal marketing`?

✔️ Fixed. Seems like I only pushed some of the PNG files for the last wrap-up-slide

**Comment by maxcapraro** [comment]
⚠️ Johhnes spotted dead links in `contact us` slide

**Comment by maxcapraro** [comment]
> ⚠️ Johhnes spotted dead links in contact us slide

Changed the linkedin link and kicked out deadlink to facebook

**Comment by rrrutledge** [comment]
Everything here looks good to me.

**Comment by maxcapraro** [comment]
Thanks @rrrutledge. I'll merge this then.

**Pull request merged**
