### PR TITLE
Create 03-keeping-the-community-healthy-it.asciidoc

### PR DESCRIPTION
**Pull request by nysenthil**
My IBM colleague Claudia Misale is a native Italian speaker. She kindly agreed to verify this machine translated Italian text with the original English source text.

### CODE REVIEW

**Comment by rrrutledge** [comment]
Thanks to @cmisale for this review ❤️ 🎉

**Review by nysenthil — COMMENTED** [review]
Hi @cmisale What a thorough and sincere review by you. It is great that our IBM Research lab has many native Italian speakers willing to help. Thank you very much for volunteering and reviewing 03-XXXX in a timely manner. I will seek your help again in a few weeks time for one more article in the Trusted Committer series. I will go ahead and merge your commit now.

**Comment by cmisale** [comment]
Very happy to help!

**Comment by rrrutledge** [comment]
Great work!  I see it live at https://innersourcecommons.org/it/learn/learning-path/trusted-committer/03/ with both @cmisale and @nysenthil listed as co-authors.  Nice!

**Pull request merged**
