### PR TITLE
Initial move of workbook introduction from Google Doc to GitHub.

### PR DESCRIPTION
**Pull request by lenucksi**
This pull request contains the Introduction section of the Learning Path Google Doc moved. 
- Currently in blank form, will be transformed to ASCIIdoc later. 
- However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

### CODE REVIEW

**Comment by rrrutledge** [comment]
> However, everyone is welcome to add the required markup as commit suggestions and I'm happy to merge them in.

If you work in a branch instead of a fork then we can submit suggestions via pull request to your branch (instead of just commit suggestions).

**Comment by rrrutledge** [comment]
Or can you give me permission to create a branch in your project fork?  I think that making a branch with all of the suggestions would be easier than a bunch of separate commit suggestions.

**Comment by lenucksi** [comment]
I'll move this over to a branch in the main repo then.

**Comment by rrrutledge** [comment]
Thanks!  Sounds great.

**Comment by lenucksi** [comment]
Just decided to let `sed` run wild on the document, markup should be good to go now.

**Comment by rrrutledge** [comment]
Great!  Will take a look.

**Pull request merged**
